accton_as5712_54x: 'https://www.dropbox.com/s/pl3cvr9olnaufw5/ONL-2.0.0_ONL-OS_2017-01-04.0024-8d23df5_AMD64_INSTALLED_INSTALLER'
accton_as6712_32x: 'https://www.dropbox.com/s/pl3cvr9olnaufw5/ONL-2.0.0_ONL-OS_2017-01-04.0024-8d23df5_AMD64_INSTALLED_INSTALLER'

virtualbox:
    # CHANGE:
    #   'power_helper_user' specifies the user to use when SSHing to the host
    #                       that is running virtualbox
    #   'power_helper_host' specifies the IP address of host that is running
    #                       virtualbox. will be dynamically set if empty string
    power_helper_user: "{{ power_helper_user | default('cord') }}"
    power_helper_host: "{{ power_helper_host | default('') }}"

maas:
    admin_email: "{{ admin_email | default('admin@cord.lab') }}"
    admin_password: "{{ password_maas_admin | default(lookup('password', 'passwords/maas_admin.txt')) }}"
    user: "{{ maas_user | default('cord') }}"
    user_password: "{{ password_maas_user | default(lookup('password', 'passwords/maas_user.txt')) }}"
    user_email: "{{ maas_email | default('cord@cord.lab') }}"
    user_sshkey: "{{ lookup('file', '/etc/maas/.ssh/cord_rsa.pub') }}"

    # CHANGE:
    #   'domain' specifies the domain name configured in to MAAS
    domain: "{{ domain | default('cord.lab') }}"
    upstream_dns: "{{ upstream_dns | default('8.8.8.8 8.8.8.4') }}"

interfaces:
    # CHANGE:
    #   'external'   specifies the interface on which the head node is
    #                connected to the internet
    #   'management' specifies the interface on which the head node will
    #                service DHCP and PXE boot requests
    fabric: "{{ fabric_iface | default('fabric') }}"
    management: "{{ management_iface | default('mgmtbr') }}"
    external: "{{ external_iface | default('') }}"

networks:
    # CHANGE:
    #   'management' specifies the network that MAAS will allocate
    #                via DHCP over the 'management' interface specified
    #                above
    #   'bridge'     specifies the network that MAAS will allocate
    #                via DHCP to the VM created in support of XOS
    #                on the head node.
    #   'fabric'     specifies the network that will be assigned to
    #                the leaf - spine fabric
    management: "{{ management_network | default('10.6.0.0/24') }}"
    bridge: "{{ bridge_network | default('172.42.0.0/24') }}"
    fabric: "{{ fabric_ip | default('10.6.1.0/24') | ipaddr('0') }}"

    # CHANGE:
    #   'bridge' name of the bride to create that is used when connecting
    #            the VMs created in support of XOS
    bridge_name: "{{ bridge_name | default('mgmtbr') }}"

ranges:
    fabric:
        low: "{{ fabric_range_low | default(fabric_ip | default('10.6.1.0/24')) | ipaddr(2) | ipaddr('address') }}"
        high: "{{ fabric_range_high | default(fabric_ip | default('10.6.1.0/24')) | ipaddr(-3) | ipaddr('address') }}"
    management:
        low: "{{ management_range_low | default(management_ip | default('10.6.0.0/24')) | ipaddr(2) | ipaddr('address') }}"
        high: "{{ management_range_high | default(management_ip | default('10.6.0.0/24')) | ipaddr(-3) | ipaddr('address') }}"

docker:
    tag: "{{ deploy_docker_tag | default('candidate') }}"
